# Generated by Django 3.0.8 on 2020-07-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Raumnummer', models.CharField(max_length=255)),
                ('Anzahl_Sitzplaetze', models.IntegerField()),
                ('Beamer', models.BooleanField()),
                ('Whiteboard', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Raumbelegung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Belegt', models.BooleanField()),
                ('Belegungsgrund', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Zeitraum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vorlesungszeit', models.TimeField()),
                ('EndTime', models.DateTimeField()),
                ('Datum', models.DateField()),
                ('StartTime', models.DateTimeField()),
            ],
        ),
    ]
