# Generated by Django 3.0.8 on 2020-08-27 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0002_buchung'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buchung',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='buchung',
            name='room',
        ),
        migrations.RemoveField(
            model_name='buchung',
            name='user',
        ),
        migrations.AddField(
            model_name='buchung',
            name='Check_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='room.Zeitraum'),
        ),
        migrations.AddField(
            model_name='buchung',
            name='Room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='room.Raum'),
        ),
        migrations.AddField(
            model_name='buchung',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='raum',
            name='Raumnummer',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
