# Generated by Django 3.0.4 on 2020-06-24 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_person', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.TextField(max_length=100)),
                ('User_to_Person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='app.Person')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Raumbelegung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_room', models.TextField(max_length=100)),
                ('Raumbelegung_to_Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raumbelegungs', to='app.Person')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.TextField(max_length=100)),
                ('Admin_to_Person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='app.Person')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
