# Generated by Django 3.0.4 on 2020-07-05 14:31

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Belegt', models.BooleanField()),
                ('Raumnummer', models.CharField(max_length=100)),
                ('Anzahl_Sitzplaetze', models.IntegerField()),
                ('Beamer', models.BooleanField()),
                ('Whiteboard', models.BooleanField()),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.RemoveField(
            model_name='raumbelegung',
            name='Raumbelegung_to_Person',
        ),
        migrations.RemoveField(
            model_name='raumbelegung',
            name='name_room',
        ),
        migrations.AddField(
            model_name='admin',
            name='Admin_to_Raumbelegung',
            field=models.ManyToManyField(related_name='admins', to='app.Raumbelegung'),
        ),
        migrations.AddField(
            model_name='admin',
            name='Admin_to_User',
            field=models.ManyToManyField(related_name='admins', to='app.User'),
        ),
        migrations.AddField(
            model_name='person',
            name='Person_to_Admin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='app.Admin'),
        ),
        migrations.AddField(
            model_name='raumbelegung',
            name='Belegungsgrund',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='raumbelegung',
            name='Raumbelegung_to_Admin',
            field=models.ManyToManyField(related_name='raumbelegungs', to='app.Admin'),
        ),
        migrations.AddField(
            model_name='raumbelegung',
            name='Raumbelegung_to_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raumbelegungs', to='app.User'),
        ),
        migrations.AddField(
            model_name='raumbelegung',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='User_to_Raumbelegung',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='app.Raumbelegung'),
        ),
        migrations.AddField(
            model_name='user',
            name='User_to_admin',
            field=models.ManyToManyField(related_name='users', to='app.Admin'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='Admin_to_Person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='app.Person'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='lastname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_to_Person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='app.Person'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Zeitraum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Datum', models.DateField()),
                ('Vorlesungszeit', models.TimeField()),
                ('Dauer', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('Zeitraum_to_Raumbelegung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zeitraums', to='app.Raumbelegung')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='WebseiteRaumbelegung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_room', models.CharField(max_length=100)),
                ('Webseiteraumbelegung_to_Raum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webseiteraumbelegungs', to='app.Raum')),
                ('Websiteraumbelegung_to_Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webseiteraumbelegungs', to='app.Person')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.AddField(
            model_name='raum',
            name='Raum_to_Admin',
            field=models.ManyToManyField(related_name='raums', to='app.Admin'),
        ),
        migrations.AddField(
            model_name='raum',
            name='Raum_to_Raumbelegung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raums', to='app.Raumbelegung'),
        ),
        migrations.AddField(
            model_name='raum',
            name='Raum_to_Zeitraum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raums', to='app.Zeitraum'),
        ),
        migrations.AddField(
            model_name='raum',
            name='Raum_to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raums', to='app.User'),
        ),
        migrations.AddField(
            model_name='admin',
            name='Admin_to_Raum',
            field=models.ManyToManyField(related_name='admins', to='app.Raum'),
        ),
        migrations.AddField(
            model_name='raumbelegung',
            name='Raumbelegung_to_Zeitraum',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raumbelegungs', to='app.Zeitraum'),
        ),
    ]
